// ダッシュボードの表示名辞書。
// Azure（Cosmos DB / Blob）上の生の名前を、「何の指標・何のデータか」が分かる日本語に変換する。
// 生の名前は小さなタグやツールチップで併記するので、調査のときは元の名前もたどれる。
//
// 構造:
//   metrics   … 指標（合計・直近7日など）の名前と説明（GA の指標説明にあたる）
//   fields    … 全アプリ共通の項目名（createdAt → 作成日時 など）
//   apps[key] … アプリごとの コンテナ名 / 埋め込み配列 / Blob コンテナ / 項目名の上書き / 値の意味
// 辞書に無い名前はそのまま表示される。アプリを増やしたら apps に足す。
window.OGS_DASHBOARD_LABELS = {
  metrics: {
    total: { name: "登録件数", desc: "コンテナに保存されているデータの総数（削除フラグ付きも含む）" },
    last7d: { name: "新規（7日）", desc: "直近 7 日間に作成されたデータの件数。作成日時の項目から数える" },
    last30d: { name: "新規（30日）", desc: "直近 30 日間に作成されたデータの件数" },
    users: { name: "利用者数", desc: "利用者を識別する項目（利用者 ID など）の異なる値の数" },
    active30d: { name: "アクティブ利用者（30日）", desc: "直近 30 日間に 1 件以上データを作った利用者の数" },
    arrayTotal: { name: "件数", desc: "1 件のデータの中に埋め込まれている配列要素の合計" },
    blobCount: { name: "ファイル数", desc: "Blob Storage に保存されているファイルの数" },
    blobBytes: { name: "容量", desc: "ファイルの合計サイズ" },
    modified30d: { name: "30日以内の更新", desc: "直近 30 日間に追加・更新されたファイルの数" },
    lastModified: { name: "最終更新", desc: "いちばん新しいファイルの更新日時" },
    health: { name: "API 稼働", desc: "各アプリのサーバー（Function App）が応答するか" },
    ru: { name: "集計コスト（RU）", desc: "この集計で Cosmos DB が消費した要求ユニット。料金の目安" },
  },

  fields: {
    id: "ID",
    createdAt: "作成日時",
    created_at: "作成日時",
    updatedAt: "更新日時",
    updated_at: "更新日時",
    timestamp: "記録日時",
    answeredAt: "回答日時",
    startedAt: "開始日時",
    finishedAt: "終了日時",
    sentAt: "送信日時",
    visitDate: "訪問日",
    date: "日付",
    lastLoginAt: "最終ログイン",
    lastStudiedAt: "最終学習日時",
    checkedAt: "確認日時",
    expiresAt: "有効期限",
    settledAt: "精算日時",
    deletedAt: "削除日時",
    deletedBy: "削除した人",
    dueAt: "復習予定日時",
    fetched_at: "取得日時",
    accepted_at: "採用日時",
    revoked_at: "無効化日時",
    userId: "利用者 ID",
    user_id: "利用者 ID",
    learnerId: "学習者 ID",
    ownerUserId: "作成者（オーナー）",
    createdBy: "記録した人",
    updatedBy: "最後に編集した人",
    apple_user_id: "Apple ID（利用者）",
    displayName: "表示名",
    display_name: "表示名",
    name: "名前",
    type: "種類",
    kind: "種類",
    status: "状態",
    role: "発言者",
    platform: "OS",
    subject: "教科",
    mode: "モード",
    strategy: "出題方法",
    questionType: "問題形式",
    splitMode: "分け方",
    environment: "課金環境",
    purpose: "用途",
    category: "カテゴリ",
    productId: "プラン",
    grade: "学年",
    ageGroup: "年齢層",
    region: "地域",
    prefecture: "都道府県",
    prefectureCode: "都道府県コード",
    entitled: "有料プラン有効",
    isCorrect: "正解",
    hintUsed: "ヒント使用",
    invalid: "無効な端末",
    period: "対象月",
    count: "回数",
    points: "ポイント",
    amount: "金額",
    memo: "メモ",
    label: "内容",
    detail: "詳細",
    title: "タイトル",
    members: "参加メンバー",
    histories: "記録",
    messages: "メッセージ",
    attachments: "添付",
    score: "得点",
    scoreRate: "正答率",
    elapsedMs: "所要時間（ms）",
    totalQuestions: "問題数",
    correctCount: "正解数",
    earnedPoints: "獲得ポイント",
    streakDays: "連続学習日数",
    badges: "バッジ",
    questionCount: "問題数",
    price: "価格",
    product_name: "商品名",
    store_name: "店名",
    purchase_date: "購入日",
    content: "本文",
    likes: "いいね数",
    visitedPrefectureCodes: "訪問した都道府県",
    year: "年度",
    month: "月",
    amountIncl: "税込金額",
    taxAmount: "消費税額",
    enteredBy: "入力者",
    receiptSeq: "領収書番号（次の値）",
    isOwner: "帳簿の持ち主",
  },

  values: {
    // 全アプリ共通の値
    platform: { ios: "iPhone / iPad", android: "Android", web: "Web" },
    environment: { Production: "本番（App Store）", Sandbox: "サンドボックス（テスト）" },
    entitled: { true: "有効", false: "無効" },
    isCorrect: { true: "正解", false: "不正解" },
    hintUsed: { true: "使った", false: "使わなかった" },
    invalid: { true: "無効", false: "有効" },
  },

  apps: {
    tsuketoku: {
      containers: {
        Groups: { name: "グループ（友達リスト・ノート・記録）", desc: "1 グループ = 1 件。立替の記録は histories に埋め込まれる" },
        GlobalSetting: { name: "アプリ共通設定", desc: "アプリ全体の設定 1 件" },
        PushTokens: { name: "通知先の端末", desc: "プッシュ通知を送る端末のトークン" },
        GroupMembers: { name: "グループメンバー（旧）", desc: "Web 版で使っていた台帳" },
        GroupHistories: { name: "記録（旧）", desc: "Web 版で使っていた台帳" },
      },
      arrays: {
        histories: "立替・割り勘の記録",
        members: "友達リスト（メンバー）",
        messages: "チャット（機能廃止・過去ログ）",
      },
      blobs: { resource: "レシート画像", tool: "配布ファイル" },
      fields: { ownerUserId: "グループの作成者", timestamp: "記録日時", memo: "メモ（○○代）" },
      values: {
        splitMode: { warikan: "わりかん", tatekae: "立替" },
      },
    },

    manatabi: {
      containers: {
        logs: { name: "行動ログ（機能の利用イベント）", desc: "どの機能がいつ使われたか。type が機能名" },
        users: { name: "利用者", desc: "端末ごとの利用者情報とポイント・訪問した都道府県" },
        visits: { name: "訪問記録", desc: "行った場所の記録（都道府県の制覇に使う）" },
        quizzes: { name: "クイズ・ゲームの問題（マスタ）", desc: "都道府県ごとの出題データ" },
        spots: { name: "おでかけスポット（マスタ）", desc: "管理画面から登録した行き先" },
        shiori: { name: "旅のしおり", desc: "家族が作った旅のしおり・おねだり" },
        discoveries: { name: "発見の投稿", desc: "旅先で見つけたものの投稿" },
        subscriptions: { name: "有料プランの購読", desc: "App Store の購読状態" },
        usage: { name: "まなぴーの月間利用回数", desc: "利用者 × 月ごとのチャット回数（無料枚数の判定用）" },
      },
      arrays: { schedule: "しおりの予定", photoUrls: "写真", answeredQuizIds: "回答したクイズ", goalAchievedDays: "目標達成日" },
      blobs: { photos: "思い出の写真", "shiori-files": "しおりの PDF", "spot-images": "スポットの画像" },
      fields: { type: "機能・種類", kind: "しおりの種類", label: "内容", count: "チャット回数" },
      values: {
        type: {
          "manapii-chat": "まなぴーとチャット",
          "daily-quiz": "今日のクイズ",
          "visit-add": "訪問記録を追加",
          "visit-update": "訪問記録を編集",
          "visit-delete": "訪問記録を削除",
          "monthly-suggestion": "今月のおすすめ旅",
          "quiz-answer": "クイズに回答",
          "game-play": "ゲームで遊ぶ",
          "shiori-create": "しおりを作成",
          "shiori-update": "しおりを更新",
          "shiori-save": "しおりを保存",
          "shiori-delete": "しおりを削除",
          "prefecture-mark": "都道府県を制覇",
          "prefecture-unmark": "都道府県の制覇を取り消し",
          "test-record": "テストの点数を記録",
          "test-record-delete": "テストの記録を削除",
          "discovery-add": "発見を投稿",
          "discovery-like": "発見にいいね",
          "discovery-delete": "発見を削除",
          "progress-reset": "進捗をリセット",
          quiz: "クイズ",
          game: "ゲーム",
          challenge: "チャレンジ",
        },
        kind: { shiori: "しおり", onedari: "おねだり" },
        status: { active: "購読中", expired: "期限切れ", revoked: "取り消し", grace: "猶予期間", billing_retry: "請求リトライ" },
      },
    },

    manabi: {
      containers: {
        learners: { name: "学習者（お子さま）", desc: "学年・ポイント・連続学習日数" },
        worksheets: { name: "取り込んだプリント", desc: "撮影したプリント 1 枚 = 1 件" },
        questions: { name: "問題", desc: "プリントから作った 1 問ずつ" },
        attempts: { name: "解答（1 問ごと）", desc: "正誤・所要時間・ヒント使用" },
        sessions: { name: "学習セッション", desc: "1 回の学習（開始〜終了）" },
        reviews: { name: "復習スケジュール", desc: "間隔反復で次に出す予定" },
      },
      blobs: { "worksheets-original": "プリントの原本（撮影画像）", "worksheets-printable": "印刷用に再組版したプリント" },
      fields: { type: "データ種別", status: "処理状態", mode: "学習モード", strategy: "出題方法" },
      values: {
        type: { learner: "学習者", worksheet: "プリント", question: "問題", attempt: "解答", session: "セッション", review: "復習" },
        subject: { kokugo: "国語", sansu: "算数", rika: "理科", shakai: "社会", eigo: "英語", other: "その他" },
        questionType: {
          kanji_write: "漢字を書く",
          kanji_read: "読みがなを書く",
          fill_blank: "空欄補充",
          multiple_choice: "選択式",
          short_answer: "記述（短答）",
          calculation: "計算",
        },
        status: { uploaded: "アップロード済み", analyzing: "解析中", ready: "出題可能", failed: "失敗" },
        mode: { app: "アプリで解く", print: "印刷して解く", handwriting: "手書きで解く" },
        strategy: { all: "全問", random: "ランダム", review: "復習", weak: "苦手優先" },
      },
    },

    kaimono: {
      containers: {
        users: { name: "利用者", desc: "Apple ID でサインインした人" },
        purchases: { name: "購入記録", desc: "買ったもの・価格・店" },
        conversations: { name: "相談スレッド", desc: "AI コンシェルジュとの会話のまとまり" },
        messages: { name: "チャットメッセージ", desc: "利用者と AI の発言 1 件ずつ" },
        purchase_proposals: { name: "AI の購入提案", desc: "会話から AI が起こした購入記録の下書き" },
        image_blobs: { name: "画像ファイルの台帳", desc: "Blob に置いた画像の管理情報" },
        refresh_tokens: { name: "ログイン継続トークン", desc: "サインイン状態を保つための内部データ" },
        url_cache: { name: "URL 取得キャッシュ", desc: "商品ページの取得結果（一時保存）" },
      },
      blobs: { "purchase-images": "購入品の写真", "chat-images": "チャットに添付した画像（7 日で自動削除）" },
      fields: { role: "発言者", purpose: "画像の用途", category: "購入カテゴリ" },
      values: {
        role: { user: "利用者", assistant: "AI コンシェルジュ", system: "システム" },
        purpose: { purchase: "購入記録", chat: "チャット" },
        category: {
          food: "食品",
          daily: "日用品",
          household: "家事・掃除",
          beauty: "美容",
          clothing: "衣類",
          medicine: "医薬品",
          baby: "ベビー",
          pet: "ペット",
          other: "その他",
          unknown: "未分類",
        },
      },
    },

    kaikei: {
      containers: {
        Records: { name: "仕訳明細（経費・売上）", desc: "1 件 = 1 明細。type で経費と売上を区別" },
        Books: { name: "年度の帳簿設定", desc: "年ごとの設定・決算調整・領収書番号" },
        Members: { name: "利用メンバー（家族）", desc: "Apple ID でサインインした人" },
      },
      arrays: { attachments: "領収書の添付" },
      blobs: { "kaikei-receipts": "領収書の画像", "kaikei-exports": "確定申告用の Excel 出力" },
      fields: { type: "明細の種類", status: "有効／削除", category: "勘定科目", year: "年度" },
      values: {
        type: { expense: "経費", income: "売上" },
        status: { "有効": "有効", "削除": "削除済み" },
      },
    },
  },
};
